export const OpenSeaERC1155ReadbleAbi = [
  'constructor(string _name, string _symbol, address _proxyRegistryAddress, string _templateURI, address _migrationAddress)',
  'event ApprovalForAll(address indexed account, address indexed operator, bool approved)',
  'event CreatorChanged(uint256 indexed _id, address indexed _creator)',
  'event MetaTransactionExecuted(address userAddress, address relayerAddress, bytes functionSignature)',
  'event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)',
  'event Paused(address account)',
  'event PermanentURI(string _value, uint256 indexed _id)',
  'event TransferBatch(address indexed operator, address indexed from, address indexed to, uint256[] ids, uint256[] values)',
  'event TransferSingle(address indexed operator, address indexed from, address indexed to, uint256 id, uint256 value)',
  'event URI(string value, uint256 indexed id)',
  'event Unpaused(address account)',
  'function ERC712_VERSION() view returns (string)',
  'function addSharedProxyAddress(address _address)',
  'function balanceOf(address _owner, uint256 _id) view returns (uint256)',
  'function balanceOfBatch(address[] accounts, uint256[] ids) view returns (uint256[])',
  'function batchBurn(address _from, uint256[] _ids, uint256[] _quantities)',
  'function batchMint(address _to, uint256[] _ids, uint256[] _quantities, bytes _data)',
  'function burn(address _from, uint256 _id, uint256 _quantity)',
  'function creator(uint256 _id) view returns (address)',
  'function disableMigrate()',
  'function executeMetaTransaction(address userAddress, bytes functionSignature, bytes32 sigR, bytes32 sigS, uint8 sigV) payable returns (bytes)',
  'function exists(uint256 _id) view returns (bool)',
  'function getChainId() view returns (uint256)',
  'function getDomainSeperator() view returns (bytes32)',
  'function getNonce(address user) view returns (uint256 nonce)',
  'function isApprovedForAll(address _owner, address _operator) view returns (bool isOperator)',
  'function isPermanentURI(uint256 _id) view returns (bool)',
  'function maxSupply(uint256 _id) pure returns (uint256)',
  'function migrate(tuple(uint256 id, address owner)[] _ownerships)',
  'function migrationTarget() view returns (address)',
  'function mint(address _to, uint256 _id, uint256 _quantity, bytes _data)',
  'function name() view returns (string)',
  'function openSeaVersion() pure returns (string)',
  'function owner() view returns (address)',
  'function pause()',
  'function paused() view returns (bool)',
  'function proxyRegistryAddress() view returns (address)',
  'function removeSharedProxyAddress(address _address)',
  'function renounceOwnership()',
  'function safeBatchTransferFrom(address _from, address _to, uint256[] _ids, uint256[] _amounts, bytes _data)',
  'function safeTransferFrom(address _from, address _to, uint256 _id, uint256 _amount, bytes _data)',
  'function setApprovalForAll(address operator, bool approved)',
  'function setCreator(uint256 _id, address _to)',
  'function setPermanentURI(uint256 _id, string _uri)',
  'function setProxyRegistryAddress(address _address)',
  'function setTemplateURI(string _uri)',
  'function setURI(uint256 _id, string _uri)',
  'function sharedProxyAddresses(address) view returns (bool)',
  'function supportsFactoryInterface() pure returns (bool)',
  'function supportsInterface(bytes4 interfaceId) view returns (bool)',
  'function symbol() view returns (string)',
  'function templateURI() view returns (string)',
  'function totalSupply(uint256 _id) view returns (uint256)',
  'function transferOwnership(address newOwner)',
  'function unpause()',
  'function uri(uint256 _id) view returns (string)',
];

export default OpenSeaERC1155ReadbleAbi;
