export const KakiCoinERC777ReadableAbi = [
  'constructor(uint256 initialSupply, address[] defaultOperators)',
  'event Approval(address indexed owner, address indexed spender, uint256 value)',
  'event AuthorizedOperator(address indexed operator, address indexed tokenHolder)',
  'event Burned(address indexed operator, address indexed from, uint256 amount, bytes data, bytes operatorData)',
  'event Minted(address indexed operator, address indexed to, uint256 amount, bytes data, bytes operatorData)',
  'event RevokedOperator(address indexed operator, address indexed tokenHolder)',
  'event Sent(address indexed operator, address indexed from, address indexed to, uint256 amount, bytes data, bytes operatorData)',
  'event Transfer(address indexed from, address indexed to, uint256 value)',
  'function allowance(address holder, address spender) view returns (uint256)',
  'function approve(address spender, uint256 value) returns (bool)',
  'function authorizeOperator(address operator)',
  'function balanceOf(address tokenHolder) view returns (uint256)',
  'function burn(uint256 amount, bytes data)',
  'function decimals() pure returns (uint8)',
  'function defaultOperators() view returns (address[])',
  'function granularity() view returns (uint256)',
  'function isOperatorFor(address operator, address tokenHolder) view returns (bool)',
  'function name() view returns (string)',
  'function operatorBurn(address account, uint256 amount, bytes data, bytes operatorData)',
  'function operatorSend(address sender, address recipient, uint256 amount, bytes data, bytes operatorData)',
  'function revokeOperator(address operator)',
  'function send(address recipient, uint256 amount, bytes data)',
  'function symbol() view returns (string)',
  'function totalSupply() view returns (uint256)',
  'function transfer(address recipient, uint256 amount) returns (bool)',
  'function transferFrom(address holder, address recipient, uint256 amount) returns (bool)',
];

export default KakiCoinERC777ReadableAbi;
